### ISSUE TITLE
Upgrade to Node 18.14 (LTS)

### ISSUE THREAD

**Issue by floric** [renovatebot/docker-renovate#1076]
Hey,

are there any impediments to upgrade to Node 18 (the current LTS release)?

If you like, I can create a MR.

Kind regards, Florian

**Comment by floric** [comment]
Ah, I just saw Renovate alreay likes to take care of it :)

https://github.com/renovatebot/docker-renovate/pull/1014

**Comment by viceice** [comment]
will be merged with next major which is around the corner

**Comment by floric** [comment]
> will be merged with next major which is around the corner

great, thanks a lot! :)
