### ISSUE TITLE
`RENOVATE_BINARY_SOURCE` overwrites userconfig

### ISSUE THREAD

**Issue by Wurstnase** [renovatebot/docker-renovate#1095]
I want a small image to update my repositories. So my first choice is the slim image.

Unfortunately it set `RENOVATE_BINARY_SOURCE=docker` and I don't want sidecars and only the `global` installed versions.
My personal config.js has
```javascript
binarySource: 'global'
``` 
which becomes overwritten.
https://github.com/renovatebot/docker-renovate/blob/efe5146545d9e9cdd5bde102d1cbfb9ce5006992/Dockerfile#L27

**Comment by viceice** [comment]
current workaround is to set binary source via ENV too.

**Comment by Wurstnase** [comment]
Thx. I make an `unset` in my pipeline before execute renovate.
