### ISSUE TITLE
Make `-slim` the default version you get when you use the `latest` tag?

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/docker-renovate#1237]
@viceice said they prefer to suggest the `-slim` image in the Renovate docs, instead of the full image.

We could go a step further, and make the `-slim` image the default when you use the `latest` tag. I don't know if this is a potentially breaking change for our users.

See the review comments in PR: https://github.com/renovatebot/renovate/pull/21222 for the full context.

**Comment by viceice** [comment]
yes, we should consider it breaking
