### ISSUE TITLE
provideing a changelog

### ISSUE THREAD

**Issue by BigMichi1** [renovatebot/docker-renovate#1660]
after now using the renvate docker image is it possible to also get the same changelog like for normal renovate updates.
when a mr for the renovate npm package is created the changelog is displayed between the versions. can the changelog also be shown when updating the renovate docker image in the MR. currently it is empty and as far i have seen they both use the same versions

**Comment by viceice** [comment]
it depends on which tag you are using. renovate can't guess from version with suffix (docker tag) to the version on the repo.

**Comment by viceice** [comment]
btw: the source url of the images are pointing to the main renovate repo.
