### ISSUE TITLE
Upgrade to Node v20 LTS

### ISSUE THREAD

**Issue by lstoeferle** [renovatebot/docker-renovate#2048]
Hi everybody,

since 24. Oct. 2023 the latest Node LTS version changed to v20 (see https://github.com/nodejs/release#release-schedule). Would it be possible to easily refactor the Docker-Image to use v20 instead of v18, or will this include also a major refactoring on the renovate core functionalities?

**Comment by viceice** [comment]
this will happen with next renovate major

**Comment by ITProKyle** [comment]
Is there an ETA for this? I've just gotten my first dependency that requires v20 so it's failing to update.

**Comment by viceice** [comment]
closing, as this repo is soon obsolete
