### ISSUE TITLE
Lock file update problem

### ISSUE THREAD

**Issue by bigstinky86** [renovatebot/docker-renovate#234]
Hello,

I'm trying to update dependency version in package.json and update package-lock.json file. Library version is updated properly but during lock file update a different issues appear. Depending on different users I use to run renovate:slim image I've got the different issues.

If I run renovate without user changing during lock file update it shows that the cache folder contains root-owned files and recommend changing user and group of files by running chown. I can because it is a docker container.

If I run with --user=0:0 flag during docker-node container run the package-lock.json file disappears and it shows no such file or directory error.

If I use full docker image it passes well but the image contains old npm and nodejs versions. I'd like to use the newer ones.

**Comment by rarkins** [comment]
Please see here for an example of customizing the full image: https://github.com/renovatebot/renovate/discussions/11846#discussioncomment-1369461

If you have any further questions, please raise a new Discussion there instead of here.

**Comment by bigstinky86** [comment]
I don't want to customize image. I need to understand why during renovate docker run it shows me lock file update problems. It uses your docker-node image.
