### ISSUE TITLE
Cron entrypoint?

### ISSUE THREAD

**Issue by RealOrangeOne** [renovatebot/docker-renovate#241]
For those of us trying to deploy Renovate using Docker, but without kubernetes, it's a bit of a pain to ensure it's run on a schedule, as docker-compose doesn't have a cron executor.

Yes it's possible to do this by running `cron` on the host, but that's not very docker native. It'd be great if there was a way to have the container deal with its own execution scheduling, perhaps using a custom entrypoint, or switching based on whether a `$CRON_SCHEDULE` environment variable exists.

Happy to contribute this, just interested in what other people think the direction should be.

**Comment by JamieMagee** [comment]
I think something like systemd timers is the right tool here. It's not very docker native, but that's because docker doesn't have any native scheduler.

`/etc/systemd/system/renovate.timer`
```
[Unit]
Description=run renovate

[Service]
Type=oneshot
ExecStart=/usr/sbin/docker run --rm docker.io/renovate/renovate:latest ...
```

**Comment by RealOrangeOne** [comment]
Well yes, I could run the scheduler outside of docker, but that means there's configuration completely separate to docker around how the container is executed, which makes maintenance a bit of a mess. If a container needs scheduling and running as a service, it should really handle itself. Adding `cron` to the container adds very little, but makes deployment so much easier.

I'm currently solving this by overriding the entrypoint of the container with something to fake cron https://github.com/RealOrangeOne/infrastructure/blob/master/ansible/roles/renovate/files/entrypoint.sh. It's a hack, but it's currently the only sane solution.
