### ISSUE TITLE
Docker image does not contain config-validator anymore

### ISSUE THREAD

**Issue by Lucas-C** [renovatebot/docker-renovate#31]
I am aware of [the breaking change introduced in v20](https://github.com/renovatebot/renovate/pull/6260).

But `dist/config-validator.js` does not seem included in the latest images:

```
$ docker run --rm --entrypoint= renovate/renovate:20.3 ls -l dist/
total 4
-rwxr-xr-x 1 root root 58 May 27 10:43 renovate.js

$ docker run --rm --entrypoint= renovate/renovate:20.10-slim ls -l dist/
total 4
-rwxr-xr-x 1 root root 58 May 28 13:03 renovate.js
```

I was able to use `node_modules/renovate/dist/config-validator.js`, but is this the expected usage ?

**Comment by rarkins** [comment]
I think this is an oversight, @viceice can hopefully confirm that soon.

**Comment by viceice** [comment]
This is expected, should we provide a `config-validator` global shortcut too, like the global `renovate` command ?

**Comment by candrews** [comment]
> This is expected, should we provide a `config-validator` global shortcut too, like the global `renovate` command ?

Yes, please!

**Comment by Lucas-C** [comment]
Thank you for adding this!

**Comment by viceice** [comment]
@Lucas-C simply run `docker run --rm -v ./config.js:/usr/src/app/config.js renovate:slim renovate-config-validator`

If you need more info open a new issue in our https://github.com/renovatebot/config-help repo
