### ISSUE TITLE
CI build broken

### ISSUE THREAD

**Issue by viceice** [renovatebot/docker-renovate#45]
```
#19 [tsbuild  9/13] RUN set -ex;   yarn build;   chmod +x dist/*.js;
  #19 0.078 + yarn build
  #19 0.251 yarn run v1.22.10
  #19 0.305 $ tsc -p tsconfig.app.json
  #19 2.466 node_modules/renovate/dist/logger/utils.d.ts(3,8): error TS1259: Module '"/usr/src/app/node_modules/@types/bunyan/index"' can only be default-imported using the 'esModuleInterop' flag
  #19 2.485 error Command failed with exit code 2.
  #19 2.485 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  #19 ERROR: executor failed running [/bin/bash -c set -ex;   yarn build;   chmod +x dist/*.js;]: buildkit-runc did not terminate successfully
```

**Comment by rarkins** [comment]
master actions: https://github.com/renovatebot/docker-renovate/actions?query=workflow%3Abuild+branch%3Amaster

Last successful Renovate update was:
![image](https://user-images.githubusercontent.com/6311784/94538133-e8fea900-0243-11eb-8d87-f1febe27a9d1.png)

**Comment by viceice** [comment]
Strange, local build succeeds

**Comment by viceice** [comment]
ok, found the issue.  We have two different imports in renovate

https://github.com/renovatebot/renovate/blob/3c99ab01086fd21d75fcab9f337ac97020c4047c/lib/logger/utils.ts#L2
https://github.com/renovatebot/renovate/blob/3c99ab01086fd21d75fcab9f337ac97020c4047c/lib/logger/index.ts#L2

We should fix them in renovate too, so `import * as bunyan from 'bunyan';` should be used. Will send a pr later.
